# Site settings
title: Science and Technology Blog
description: "Blog site for scientific/technical pages."
url: "https://k8-sand.github.io/rdac-site/"
author:
  name: "DUKE RDAC"
  url: "https://sites.globalhealth.duke.edu/rdac/"

# Build settings
baseurl: /rdac-site/
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
genre: "Science and Technology Blog" # Blog genre
version: "1.0.1"    # Blog site version

# Disqus comments
comments: true      # used to enable disqus comments on site
dsq_shortname: science-blog-template # disqus shortname

# Options: Define which header/footer to use
custom_header: false
custom_nav_footer: false
reverse: false

# Plugins
plugins:
  - jekyll-paginate
